import datetime

import matplotlib.pyplot as plt
import mplcursors
import pandas as pd


def plot_shotchart(shotchart_df, clutch=False, **kwargs):
    """
        Takes the shot_df generated by 'shot_chart_to_pandas' attribute of 'NBA_player_stat' class
        as input and the arguments below to plot a desired shot chart on an NBA half-court image file.

        **cluth
        If 'clutch' argument is True:
            A shotchart will be drawn only for shots under clutch time.
            The clutch time is defined as:
            "During the 4th quarter or overtime, with less than five minutes remaining,
             and neither team ahead by more than five points."
        Clutch argument can be combined with any or all **kwargs argument(s).


        **kwags include:
        1) date: search for shots in a single game on the specified date
            input format example = [2018,10,17]
        2) month: search for all shots in the specified month
            input format example = 11
        3) period: search for all shots during the specified period of time
            input format example = [[2018,10,25], [2019,1,1]]
        4) team: search for all shots against the specified team
            input format example = 'OKC'
        5) HW: search for all shots on games at Home ('home') or on the Road ('road')
            input format example = 'road'
        6) Qtr: Search for all shots in the specified quarter
            input format example = 3

        If not defined, a shotchart for all shots across the whole season will be drawn.

        The **kwargs parameters can be combined:
            i.e. plot_shotchart(shotchartDF, monnth=12, team='OKC', Qtr=4)

    """

    player_shotchart_df = shotchart_df

    if 'date' in kwargs:
        search_date = kwargs['date']
        player_shotchart_df = player_shotchart_df.loc[
            (pd.to_datetime(player_shotchart_df['Date']).dt.year == search_date[0]) &
            (pd.to_datetime(player_shotchart_df['Date']).dt.month == search_date[1]) &
            (pd.to_datetime(player_shotchart_df['Date']).dt.day == search_date[2])
            ]
    if 'month' in kwargs:
        search_month = kwargs['month']
        player_shotchart_df = player_shotchart_df.loc[
            pd.to_datetime(player_shotchart_df['Date']).dt.month == search_month]

    if 'period' in kwargs:
        search_period = kwargs['period']
        mask = (player_shotchart_df.Date >= datetime.date(*search_period[0])) & (
                player_shotchart_df.Date <= datetime.date(*search_period[1]))
        player_shotchart_df = player_shotchart_df.loc[mask]

    if 'team' in kwargs:
        search_team = kwargs['team']
        player_shotchart_df = player_shotchart_df.loc[player_shotchart_df.Against == search_team]

    if 'HW' in kwargs:
        search_hw = kwargs['HW']
        player_shotchart_df = player_shotchart_df.loc[player_shotchart_df.Home_Road == search_hw]

    if 'Qtr' in kwargs:
        search_qtr = kwargs['Qtr']
        player_shotchart_df = player_shotchart_df.loc[player_shotchart_df.Qtr == search_qtr]

    if clutch:
        player_shotchart_df = player_shotchart_df.loc[(player_shotchart_df.Qtr == 4) &  # Clutch Condition 1
                                                      (player_shotchart_df.TimeLeft < datetime.time(0, 5,
                                                                                                    0)) &  # Clutch Condition 2
                                                      (abs(
                                                          player_shotchart_df.Team_score - player_shotchart_df.Opp_Score) <= 5)
            # Clutch Condition 3
                                                      ]

    fig, ax = plt.subplots(figsize=(8, 8))
    ax.scatter(player_shotchart_df.loc[player_shotchart_df.make == 'make', 'left_coord'],
               player_shotchart_df.loc[player_shotchart_df.make == 'make', 'top_coord'],
               marker='o', c='b', alpha=0.7)
    ax.scatter(player_shotchart_df.loc[player_shotchart_df.make != 'make', 'left_coord'],
               player_shotchart_df.loc[player_shotchart_df.make != 'make', 'top_coord'],
               marker='x', c='r', alpha=0.7)
    img = plt.imread("../nbahalfcourt.png")
    ax.imshow(img, alpha=1)
    mplcursors.cursor(hover=True)

    return fig
